# Generated by Django 4.2.2 on 2023-07-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentdetail_loan_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='paymentdetail',
            table='paymentdetail',
        ),
    ]
