# Generated by Django 4.2.2 on 2023-07-03 05:40

from django.db import migrations, models
import django.db.models.deletion
import loan.constants
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_created_at_alter_customer_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=12, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.SmallIntegerField(default=loan.constants.Status['PENDING'])),
                ('maximum_payment', models.DateTimeField()),
                ('taken_at', models.DateTimeField()),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
