# Generated by Django 4.2.2 on 2023-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='maximum_payment',
            new_name='maximum_payment_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='external_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
