# Generated by Django 4.2.2 on 2023-07-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_amount_alter_loan_outstanding'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='loan',
        ),
    ]
