# Generated by Django 4.2.2 on 2023-06-28 01:36

import customer.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('external_id', models.CharField(max_length=12)),
                ('status', models.SmallIntegerField(default=customer.constants.Status['INACTIVE'])),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preapproved_at', models.DateTimeField()),
            ],
        ),
    ]
