# Generated by Django 4.2.2 on 2023-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_created_at_alter_customer_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
